# Generated by Django 6.0.4 on 2026-04-30 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='External session identifier', max_length=100, unique=True)),
                ('title', models.CharField(blank=True, default='New Session', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('device_context', models.JSONField(blank=True, default=dict, help_text='Devices being discussed in this session')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('sources', models.JSONField(blank=True, default=list, help_text='Manual sections cited in this response')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context (device data, confidence, etc.)')),
                ('token_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='troubleshooter.chatsession')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalManual',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_type', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(help_text='Section/chapter title', max_length=300)),
                ('content', models.TextField(help_text='Manual text content (chunk)')),
                ('chunk_index', models.IntegerField(default=0, help_text='Position within the full manual')),
                ('embedding', models.BinaryField(blank=True, help_text='Serialized embedding vector for FAISS', null=True)),
                ('word_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['device_type', 'brand', 'chunk_index'],
                'indexes': [models.Index(fields=['device_type'], name='troubleshoo_device__d36699_idx'), models.Index(fields=['brand'], name='troubleshoo_brand_d5b480_idx')],
            },
        ),
    ]
