# Generated by Django 6.0.4 on 2026-04-30 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentialHealthSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(help_text='Residential Health Score (0–100)')),
                ('grade', models.CharField(default='A', help_text='Letter grade (A+, A, B, C, D, F)', max_length=2)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('breakdown', models.JSONField(default=dict, help_text='{"uptime": 95, "anomalies": 88, "power": 92, "errors": 97}')),
                ('summary', models.TextField(blank=True, help_text='AI-generated natural language summary')),
                ('device_count', models.IntegerField(default=0)),
                ('online_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-calculated_at'],
                'get_latest_by': 'calculated_at',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('floor', models.IntegerField(choices=[(0, 'Basement'), (1, 'Ground Floor'), (2, 'First Floor'), (3, 'Second Floor')], default=1)),
                ('svg_path_id', models.CharField(blank=True, help_text='SVG element ID for floorplan interactivity', max_length=50)),
                ('svg_coordinates', models.JSONField(blank=True, default=dict, help_text='{"x": 0, "y": 0, "width": 100, "height": 80}')),
                ('icon', models.CharField(default='room', help_text='Icon identifier', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['floor', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('device_type', models.CharField(choices=[('thermostat', 'Thermostat'), ('smart_lock', 'Smart Lock'), ('light', 'Smart Light'), ('camera', 'Security Camera'), ('sensor', 'Sensor'), ('appliance', 'Smart Appliance'), ('speaker', 'Smart Speaker'), ('hvac', 'HVAC System'), ('doorbell', 'Smart Doorbell'), ('plug', 'Smart Plug')], max_length=30)),
                ('node_id', models.CharField(help_text='Matter/HA Node ID (e.g., node-0x01)', max_length=20, unique=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('warning', 'Warning'), ('critical', 'Critical')], default='online', max_length=20)),
                ('power_consumption_watts', models.FloatField(default=0.0)),
                ('battery_level', models.IntegerField(blank=True, help_text='Battery % (null if AC-powered)', null=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_reachable', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Device-specific attributes (e.g., temperature setpoint, lock state)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dashboard.room')),
            ],
            options={
                'ordering': ['room', 'name'],
                'indexes': [models.Index(fields=['status'], name='dashboard_d_status_12ae05_idx'), models.Index(fields=['device_type'], name='dashboard_d_device__c331bd_idx'), models.Index(fields=['node_id'], name='dashboard_d_node_id_f9f48c_idx')],
            },
        ),
    ]
