# Generated by Django 6.0.4 on 2026-04-30 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_home_alter_room_name_room_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentialhealthsnapshot',
            name='home',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_snapshots', to='dashboard.home'),
        ),
    ]
