# Generated by Django 6.0.4 on 2026-04-30 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterNode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('node_id', models.CharField(help_text='Matter Node ID', max_length=20)),
                ('endpoint_id', models.IntegerField(default=0, help_text='Matter Endpoint (0 = root)')),
                ('cluster_type', models.CharField(choices=[('0x0006', 'On/Off'), ('0x0008', 'Level Control'), ('0x0028', 'Basic Information'), ('0x002f', 'Power Source'), ('0x0101', 'Door Lock'), ('0x0201', 'Thermostat'), ('0x0300', 'Color Control'), ('0x0400', 'Illuminance Measurement'), ('0x0402', 'Temperature Measurement'), ('0x0405', 'Relative Humidity'), ('0x0406', 'Occupancy Sensing')], help_text='Matter Cluster ID (hex)', max_length=10)),
                ('cluster_name', models.CharField(blank=True, max_length=100)),
                ('health_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('critical', 'Critical')], default='healthy', max_length=20)),
                ('anomaly_score', models.FloatField(default=0.0, help_text='LSTM-based anomaly score (0.0 = normal, 1.0 = critical)')),
                ('last_diagnostic', models.DateTimeField(auto_now=True)),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Cluster-specific attribute values')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_nodes', to='dashboard.device')),
            ],
            options={
                'ordering': ['-anomaly_score'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('power', 'Power (W)'), ('vibration', 'Vibration (m/s²)'), ('temperature', 'Temperature (°C)'), ('voltage', 'Voltage (V)'), ('current', 'Current (A)'), ('signal_strength', 'Signal Strength (dBm)'), ('error_count', 'Error Count')], max_length=30)),
                ('value', models.FloatField()),
                ('unit', models.CharField(max_length=20)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('is_anomalous', models.BooleanField(default=False)),
                ('z_score', models.FloatField(default=0.0, help_text='Statistical z-score from baseline')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_logs', to='diagnostics.matternode')),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='matternode',
            index=models.Index(fields=['health_status'], name='diagnostics_health__157e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='matternode',
            index=models.Index(fields=['anomaly_score'], name='diagnostics_anomaly_c2eaaa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='matternode',
            unique_together={('device', 'endpoint_id', 'cluster_type')},
        ),
        migrations.AddIndex(
            model_name='diagnosticlog',
            index=models.Index(fields=['metric_type', 'recorded_at'], name='diagnostics_metric__10da57_idx'),
        ),
        migrations.AddIndex(
            model_name='diagnosticlog',
            index=models.Index(fields=['is_anomalous'], name='diagnostics_is_anom_89e507_idx'),
        ),
    ]
