# Generated by Django 6.0.4 on 2026-04-30 12:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('troubleshooter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_latency_ms', models.IntegerField(default=0, help_text='End-to-end response time')),
                ('p95_latency_ms', models.IntegerField(default=0, help_text='P95 latency across steps')),
                ('total_tokens', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('estimated_cost_usd', models.FloatField(default=0.0)),
                ('steps_count', models.IntegerField(default=0)),
                ('retrieval_count', models.IntegerField(default=0, help_text='Number of RAG retrievals')),
                ('tools_invoked', models.IntegerField(default=0, help_text='Total tool calls')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='troubleshooter.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThoughtTrace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField(help_text='Execution order within the pipeline')),
                ('step_type', models.CharField(choices=[('intent', 'Intent Classification'), ('diagnostic', 'Hardware Diagnostics'), ('retrieval', 'Knowledge Retrieval'), ('response', 'Response Synthesis'), ('tool_call', 'Tool Invocation'), ('error', 'Error Recovery')], max_length=20)),
                ('agent_name', models.CharField(blank=True, help_text='Which agent handled this step', max_length=100)),
                ('input_summary', models.TextField(blank=True, help_text='Summarized input to this step')),
                ('output_summary', models.TextField(blank=True, help_text='Summarized output from this step')),
                ('duration_ms', models.IntegerField(default=0, help_text='Step execution time in milliseconds')),
                ('token_count', models.IntegerField(default=0, help_text='Tokens consumed in this step')),
                ('tools_used', models.JSONField(blank=True, default=list, help_text='List of tools invoked during this step')),
                ('raw_output', models.JSONField(blank=True, default=dict, help_text='Full raw output for debugging')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traces', to='troubleshooter.message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thought_traces', to='troubleshooter.chatsession')),
            ],
            options={
                'ordering': ['session', 'step_order'],
                'indexes': [models.Index(fields=['step_type'], name='observabili_step_ty_ededa3_idx'), models.Index(fields=['session', 'step_order'], name='observabili_session_a383b1_idx')],
            },
        ),
    ]
